from typing import Dict, List
from src.models.feature import Domain


UNIVERSAL_TAXONOMY: Dict[str, Domain] = {
    "data_operations": Domain(
        name="Data Operations",
        description="Data loading, processing, transformation, and storage",
        subdomains=[
            "file_io",
            "database",
            "streaming",
            "serialization",
            "parsing",
            "validation",
            "transformation",
            "aggregation",
        ],
        keywords=["data", "file", "database", "stream", "parse", "transform"],
        typical_features=["Load CSV", "Database query", "Data validation", "JSON parsing"],
    ),
    "api_web": Domain(
        name="API & Web Services",
        description="RESTful APIs, GraphQL, webhooks, and web services",
        subdomains=[
            "rest_api",
            "graphql",
            "websockets",
            "authentication",
            "rate_limiting",
            "middleware",
            "routing",
            "serialization",
        ],
        keywords=["api", "rest", "http", "endpoint", "request", "response"],
        typical_features=["Create REST endpoint", "JWT authentication", "API rate limiting"],
    ),
    "machine_learning": Domain(
        name="Machine Learning",
        description="ML models, training, inference, and evaluation",
        subdomains=[
            "supervised",
            "unsupervised",
            "reinforcement",
            "deep_learning",
            "feature_engineering",
            "model_evaluation",
            "hyperparameter_tuning",
            "deployment",
        ],
        keywords=["ml", "model", "training", "prediction", "neural", "algorithm"],
        typical_features=["Train classifier", "Model evaluation", "Feature scaling"],
    ),
    "data_visualization": Domain(
        name="Data Visualization",
        description="Charts, graphs, dashboards, and visual analytics",
        subdomains=[
            "charts",
            "plots",
            "dashboards",
            "interactive",
            "3d_visualization",
            "maps",
            "reports",
            "export",
        ],
        keywords=["plot", "chart", "graph", "dashboard", "visual", "display"],
        typical_features=["Line chart", "Interactive dashboard", "Export to PDF"],
    ),
    "authentication_security": Domain(
        name="Authentication & Security",
        description="User auth, encryption, access control, and security",
        subdomains=[
            "authentication",
            "authorization",
            "encryption",
            "oauth",
            "jwt",
            "rbac",
            "password_management",
            "security_audit",
        ],
        keywords=["auth", "security", "encrypt", "token", "permission", "access"],
        typical_features=["User login", "JWT tokens", "Role-based access control"],
    ),
    "testing_quality": Domain(
        name="Testing & Quality Assurance",
        description="Unit tests, integration tests, and quality metrics",
        subdomains=[
            "unit_testing",
            "integration_testing",
            "e2e_testing",
            "mocking",
            "coverage",
            "performance_testing",
            "load_testing",
            "test_automation",
        ],
        keywords=["test", "assert", "mock", "coverage", "validate", "qa"],
        typical_features=["Unit test", "Mock external API", "Code coverage report"],
    ),
    "async_concurrency": Domain(
        name="Async & Concurrency",
        description="Asynchronous operations, threading, and parallel processing",
        subdomains=[
            "async_await",
            "threading",
            "multiprocessing",
            "task_queue",
            "event_loop",
            "coroutines",
            "synchronization",
            "parallel_execution",
        ],
        keywords=["async", "thread", "parallel", "concurrent", "queue", "worker"],
        typical_features=["Async HTTP requests", "Task queue", "Thread pool"],
    ),
    "caching_optimization": Domain(
        name="Caching & Optimization",
        description="Performance optimization, caching strategies, and efficiency",
        subdomains=[
            "memory_cache",
            "distributed_cache",
            "query_optimization",
            "lazy_loading",
            "compression",
            "indexing",
            "profiling",
            "benchmarking",
        ],
        keywords=["cache", "optimize", "performance", "speed", "efficient", "fast"],
        typical_features=["Redis cache", "Query optimization", "Lazy loading"],
    ),
    "logging_monitoring": Domain(
        name="Logging & Monitoring",
        description="Application logging, monitoring, and observability",
        subdomains=[
            "structured_logging",
            "log_aggregation",
            "metrics",
            "alerts",
            "tracing",
            "debugging",
            "health_checks",
            "dashboards",
        ],
        keywords=["log", "monitor", "alert", "metric", "trace", "debug"],
        typical_features=["Structured logging", "Metrics collection", "Health endpoint"],
    ),
    "error_handling": Domain(
        name="Error Handling & Resilience",
        description="Exception handling, retry logic, and fault tolerance",
        subdomains=[
            "exception_handling",
            "retry_logic",
            "circuit_breaker",
            "fallback",
            "validation",
            "error_recovery",
            "graceful_degradation",
            "timeout_handling",
        ],
        keywords=["error", "exception", "retry", "fallback", "handle", "recover"],
        typical_features=["Retry with backoff", "Circuit breaker", "Error reporting"],
    ),
    "configuration": Domain(
        name="Configuration Management",
        description="Config loading, environment variables, and settings",
        subdomains=[
            "config_files",
            "environment_vars",
            "secrets_management",
            "feature_flags",
            "hot_reload",
            "validation",
            "hierarchical_config",
            "remote_config",
        ],
        keywords=["config", "settings", "environment", "secrets", "flags"],
        typical_features=["Load config file", "Environment variables", "Feature flags"],
    ),
    "cli_interface": Domain(
        name="CLI & Command-Line Interface",
        description="Command-line tools, arguments, and interactive shells",
        subdomains=[
            "argument_parsing",
            "subcommands",
            "interactive_prompts",
            "progress_bars",
            "output_formatting",
            "autocompletion",
            "help_generation",
            "config_files",
        ],
        keywords=["cli", "command", "terminal", "args", "shell", "interactive"],
        typical_features=["Argument parser", "Progress bar", "Interactive prompts"],
    ),
    "file_system": Domain(
        name="File System Operations",
        description="File and directory operations, path handling, and I/O",
        subdomains=[
            "file_operations",
            "directory_operations",
            "path_handling",
            "file_watching",
            "temp_files",
            "permissions",
            "compression",
            "search",
        ],
        keywords=["file", "directory", "path", "folder", "io", "disk"],
        typical_features=["File watcher", "Directory traversal", "Path validation"],
    ),
    "database_orm": Domain(
        name="Database & ORM",
        description="Database connections, queries, ORM, and migrations",
        subdomains=[
            "connections",
            "queries",
            "orm_models",
            "migrations",
            "transactions",
            "indexing",
            "relationships",
            "connection_pooling",
        ],
        keywords=["database", "sql", "orm", "query", "model", "migration"],
        typical_features=["ORM models", "Database migrations", "Query builder"],
    ),
    "messaging_queues": Domain(
        name="Messaging & Queues",
        description="Message queues, pub/sub, and event-driven architecture",
        subdomains=[
            "message_queue",
            "pub_sub",
            "event_bus",
            "task_queue",
            "stream_processing",
            "retry_logic",
            "dead_letter_queue",
            "routing",
        ],
        keywords=["queue", "message", "pubsub", "event", "broker", "topic"],
        typical_features=["Task queue", "Pub/sub messaging", "Event bus"],
    ),
    "search_indexing": Domain(
        name="Search & Indexing",
        description="Full-text search, indexing, and search optimization",
        subdomains=[
            "full_text_search",
            "indexing",
            "query_parsing",
            "relevance_ranking",
            "faceted_search",
            "autocomplete",
            "fuzzy_matching",
            "search_analytics",
        ],
        keywords=["search", "index", "query", "find", "elasticsearch", "relevance"],
        typical_features=["Full-text search", "Search indexing", "Autocomplete"],
    ),
    "notifications": Domain(
        name="Notifications & Alerts",
        description="Email, SMS, push notifications, and alerting",
        subdomains=[
            "email",
            "sms",
            "push_notifications",
            "webhooks",
            "in_app_notifications",
            "templates",
            "scheduling",
            "delivery_tracking",
        ],
        keywords=["notification", "email", "sms", "push", "alert", "message"],
        typical_features=["Send email", "Push notifications", "Alert system"],
    ),
    "scheduling_cron": Domain(
        name="Scheduling & Cron Jobs",
        description="Task scheduling, cron jobs, and periodic execution",
        subdomains=[
            "cron_jobs",
            "task_scheduling",
            "periodic_tasks",
            "job_queue",
            "delayed_execution",
            "calendar_scheduling",
            "retry_scheduling",
            "job_monitoring",
        ],
        keywords=["schedule", "cron", "job", "periodic", "task", "timer"],
        typical_features=["Cron job", "Task scheduler", "Periodic tasks"],
    ),
    "payment_billing": Domain(
        name="Payment & Billing",
        description="Payment processing, billing, and subscription management",
        subdomains=[
            "payment_processing",
            "subscriptions",
            "invoicing",
            "refunds",
            "payment_methods",
            "billing_cycles",
            "webhooks",
            "compliance",
        ],
        keywords=["payment", "billing", "subscription", "invoice", "stripe", "charge"],
        typical_features=["Process payment", "Subscription management", "Invoice generation"],
    ),
    "file_upload": Domain(
        name="File Upload & Storage",
        description="File uploads, cloud storage, and media management",
        subdomains=[
            "file_upload",
            "cloud_storage",
            "image_processing",
            "video_processing",
            "cdn_integration",
            "storage_quota",
            "file_validation",
            "thumbnail_generation",
        ],
        keywords=["upload", "storage", "cloud", "s3", "file", "media"],
        typical_features=["File upload", "S3 storage", "Image resize"],
    ),
    "realtime_communication": Domain(
        name="Real-time Communication",
        description="WebSockets, real-time updates, and live features",
        subdomains=[
            "websockets",
            "server_sent_events",
            "real_time_updates",
            "chat",
            "notifications",
            "presence",
            "broadcasting",
            "connection_management",
        ],
        keywords=["realtime", "websocket", "live", "chat", "push", "socket"],
        typical_features=["WebSocket server", "Live updates", "Chat system"],
    ),
    "export_import": Domain(
        name="Export & Import",
        description="Data export/import, format conversion, and bulk operations",
        subdomains=[
            "csv_export",
            "json_export",
            "pdf_generation",
            "excel_export",
            "bulk_import",
            "format_conversion",
            "template_based",
            "streaming_export",
        ],
        keywords=["export", "import", "download", "convert", "format", "bulk"],
        typical_features=["CSV export", "PDF generation", "Bulk import"],
    ),
    "pagination_filtering": Domain(
        name="Pagination & Filtering",
        description="Data pagination, filtering, sorting, and search",
        subdomains=[
            "pagination",
            "filtering",
            "sorting",
            "search",
            "facets",
            "cursors",
            "infinite_scroll",
            "query_builder",
        ],
        keywords=["pagination", "filter", "sort", "search", "page", "limit"],
        typical_features=["Paginated API", "Advanced filtering", "Sort by field"],
    ),
    "user_management": Domain(
        name="User Management",
        description="User profiles, roles, permissions, and account management",
        subdomains=[
            "user_profiles",
            "registration",
            "roles",
            "permissions",
            "account_settings",
            "password_reset",
            "user_search",
            "profile_pictures",
        ],
        keywords=["user", "profile", "account", "role", "permission", "registration"],
        typical_features=["User registration", "Profile management", "Role assignment"],
    ),
    "workflow_automation": Domain(
        name="Workflow & Automation",
        description="Workflow engines, automation, and business process management",
        subdomains=[
            "workflow_engine",
            "state_machines",
            "automation_rules",
            "approval_flows",
            "triggers",
            "actions",
            "conditions",
            "orchestration",
        ],
        keywords=["workflow", "automation", "process", "trigger", "action", "flow"],
        typical_features=["Workflow engine", "Approval flow", "Automation rules"],
    ),
}


def get_all_domains() -> List[str]:
    """Get list of all domain names"""
    return list(UNIVERSAL_TAXONOMY.keys())


def get_domain(domain_name: str) -> Domain:
    """Get domain by name"""
    return UNIVERSAL_TAXONOMY.get(domain_name)


def get_all_subdomains() -> Dict[str, List[str]]:
    """Get all subdomains organized by domain"""
    return {name: domain.subdomains for name, domain in UNIVERSAL_TAXONOMY.items()}


def get_taxonomy_stats() -> Dict[str, int]:
    """Get taxonomy statistics"""
    total_subdomains = sum(len(d.subdomains) for d in UNIVERSAL_TAXONOMY.values())
    return {
        "total_domains": len(UNIVERSAL_TAXONOMY),
        "total_subdomains": total_subdomains,
        "avg_subdomains_per_domain": total_subdomains / len(UNIVERSAL_TAXONOMY),
    }
